name: tests
on: [workflow_call]
jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: dsctiet19/dsc-bootcamp-feedback-server:latest
